### PR TITLE
Support using a system installation of Eigen via eigen_catkin

### PR DESCRIPTION
**Pull request by HannesSommer**
The default is NOT to use the system library, just as before.

BUT when use-system-installation-of-eigen.cmake sets  `USE_SYSTEM_EIGEN` to `ON` eigen_catkin  switches to the system library (for all its dependees) or fails if there is none. 

I was thinking of maintain another branch that has one commit difference to master with this very change. This would allow selecting system library or not via `rosws` tool (by choosing a branch for eigen_catkin).

(background problem here is that SchweizerMesser switched to using eigen_catkin and kalibr isn't using it currently)

@schneith  does that make sense?
Is there a simpler solution?

### CODE REVIEW

**Comment by HannesSommer** [comment]
Anybody willing to review?

This is an important feature as in some situations mixing different Eigen versions (e.g. 3.2.0 as in Ubuntu 14.04, with 3.2.7 as currently in this master) in one executable - even through independent (!) shared libraries only linked together in one executable may lead to very hard to understand crashes.

**Comment by schneith** [comment]
@HannesSommer sorry, i somehow missed this PR. at the moment i'm a bit busy with icra stuff and would prefer not to mess with my installation. 
@dymczykm would you maybe have time to tal?

**Comment by HannesSommer** [comment]
No problem. I understand that :). For the moment I would consider using a system installation of eigen through eigen_catkin an experimental feature. 
To merge this PR in it is IMO enough to be sure that without turning it on (default is OFF) it behaves exactly as before.

**Comment by helenol** [comment]
@HannesSommer, @schneith, @mfehr -- taking this over to enforce minimum Eigen version, otherwise take system Eigen by default as agreed with @schneith to fix awful awful Eigen memory alignment bugs on 16.04 with Kinetic (which pulls in a newer version than this that is incompatible).

**Comment by helenol** [comment]
So added some horrible horrible stuff since no two FindEigen3.cmake are alike. Tested on OS X and 16.04 so far, will set up a jenkins job for all 3...

**Comment by helenol** [comment]
test this please

**Comment by helenol** [comment]
add to whitelist

**Pull request merged**
